<?php

/**
 * @file
 * Contains gdpr_tag_manager
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_page_attachments().
 */

function gdpr_tag_manager_page_attachments_alter(&$page) {
  $config = \Drupal::config('gdpr_tag_manager.settings');

  if ($config->get('activate') == 1) {
    $page['#attached']['library'][] = 'gdpr_tag_manager/gdpr_tag_manager_lib';
    $page['#attached']['drupalSettings']['pop_up_msg'] = $config->get('pop_up_msg');
    $page['#attached']['drupalSettings']['pop_up_scroll'] = $config->get('pop_up_scroll');
    $page['#attached']['drupalSettings']['privacy_policy_link'] = $config->get('privacy_policy_link');
    $page['#attached']['drupalSettings']['gtm_container'] = $config->get('gtm_container');
    $page['#attached']['drupalSettings']['cookie_duration'] = $config->get('cookie_duration');
    $page['#attached']['drupalSettings']['cookie_activate'] = $config->get('cookie_activate');
    $page['#attached']['drupalSettings']['show_popup_us'] = $config->get('show_popup_us');
    $page['#attached']['drupalSettings']['link_text'] = $config->get('link_text');
    $page['#attached']['drupalSettings']['pop_up_position'] = $config->get('pop_up_position');
    $page['#attached']['drupalSettings']['button_color'] = $config->get('button_color');
    $page['#attached']['drupalSettings']['background_color'] = $config->get('background_color');
  }
}
